# [Python: Numpy-массивы](https://ru.hexlet.io/courses/python-numpy)

## [Испытания](https://ru.hexlet.io/courses/python-numpy#challenges)

### [Успешные группы](https://ru.hexlet.io/challenges/python_numpy_student_grades_exercise/instance)

https://ru.hexlet.io/code_reviews/1574111

In [1]:
import numpy as np

In [33]:
def better_in_subject(array1: np.array, array2: np.array, subject: str) -> int:
    subjects = ['Math', 'Chemistry', 'Physics', 'Literature']
    col_num = subjects.index(subject)
    array1_subject_mean = array1[:,col_num].mean()
    array2_subject_mean = array2[:,col_num].mean()
    return 1 if array1_subject_mean > array2_subject_mean else 2


def get_above_average(array1: np.array, array2: np.array, array_number: int) -> int:
    array = array1 if array_number == 1 else array2
    mean_grades = array.mean(axis=0)
    return ((array > mean_grades).sum(axis=0) / array.shape[0] * 100).round(2)

In [15]:
print(better_in_subject(grades_1, grades_2, 'Math')) # 2
print(better_in_subject(grades_1, grades_2, 'Physics')) # 1
print(better_in_subject(grades_1, grades_2, 'Literature')) # 1

2
1
1


In [17]:
# каждый ряд - оценки студента
# по предметам: Math, Chemistry, Physics, Literature
grades_1 = np.array([[2, 2, 5, 3], [3, 4, 2, 5], [3, 5, 5, 4], [4, 4, 5, 2], [5, 5, 4, 5]])
grades_2 = np.array([[5, 3, 3, 5], [4, 5, 4, 5], [3, 2, 2, 2], [3, 2, 2, 2], [5, 2, 4, 2]])

In [19]:
get_above_average(grades_1, grades_2, 1) # [40., 80., 80., 60.]

array([40., 40., 60., 60.])

### [Анализ погоды](https://ru.hexlet.io/challenges/python_numpy_temperatures_exercise)

https://ru.hexlet.io/code_reviews/1576923

Напишите функцию anomalous_days_count, которая принимает массив температур за месяц и возвращает количество аномальных дней в месяце. Аномальными дни считаются, если температура за день отличается от средней скользящей (с окном в 5 дней) на 5 и больше градусов.

`days = [12, 16, 20, 32, 24, 22, 12, 18]`

средние скользящие с окном в 5 дней будут [nan, nan, nan, nan, 20.8, 22.8, 22.0, 21.6]
тогда разницы со средними будут как [nan, nan, nan, nan, 3.2, 0.8, 10.0, 3.6]
отсюда видно, что у нас 2 аномальных дня

`anomalous_days_count(days) # 2`

2) Напишите функцию stable_days_count, которая принимает массив температур за месяц и возвращает количество стабильных дней в месяце. Стабильными дни считаются, если температура за день не отличается от средней скользящей (с окном в 5 дней) больше чем на 2 градуса.

`days = [12, 16, 20, 32, 24, 22, 12, 18]`

средние скользящие с окном в 5 дней будут [nan, nan, nan, nan, 20.8, 22.8, 22.0, 21.6]
огда разницы со средними будут как [nan, nan, nan, nan, 3.2, 0.8, 10.0, 3.6]
отсюда видно, что есть 1 стабильный день

`stable_days_count(days) # 1`

3) Напишите функцию max_stable_period, которая принимает массив температур и возвращает максимальную продолжительность периода стабильных дней. Стабильными дни считаются, если температура за день не отличается от средней скользящей (с окном в 5 дней) больше чем на 2 градуса.

`days = [12, 16, 20, 32, 24, 22, 12, 18]`

средние скользящие с окном в 5 дней будут [nan, nan, nan, nan, 20.8, 22.8, 22.0, 21.6]
тогда разницы со средними будут как [nan, nan, nan, nan, 3.2, 0.8, 10.0, 3.6]
отсюда видно, что есть всего 1 стабильный день подряд

`max_stable_period(days) # 1`

Подсказки

Среднее скользящее расчитывается как среднее периода. Если невозможно расчитать за предыдущие дни, то задайте его как nan. Например для массива [1, 2, 3] скользящие будут [nan, nan, 2.0]


In [3]:
def moving_average(array: np.array, window):
    nan_section = np.full(min((array_len := len(array)), window - 1), np.nan)
    if array_len <= window - 1:
        return nan_section
    values_section = np.array([array[i - window:i].mean() for i in range(window, array_len + 1)])
    return np.hstack([nan_section, values_section])


def anomalous_days_count(array, window=5, abnormal_diff=5):
    if isinstance(array, list):
        array = np.array(array)
    moving_averages = moving_average(array, window)
    diffs = np.abs(moving_averages - array)
    # print(diffs)
    return len(diffs[diffs >= abnormal_diff])

def stable_days_count(array, window=5, stable_diff=2):
    if isinstance(array, list):
        array = np.array(array)
    moving_averages = moving_average(array, window)
    diffs = np.abs(moving_averages - array)
    # print(diffs)
    return len(diffs[diffs <= stable_diff])


def max_stable_period(array, window=5, stable_diff=2):
    if isinstance(array, list):
        array = np.array(array)
    stable_days_mask = _stable_days_mask(array, window, stable_diff)
    return _longest_constant_series(stable_days_mask, True)


def _stable_days_mask(array: np.array, window, stable_diff):
    moving_averages = moving_average(array, window)
    diffs = np.abs(moving_averages - array)
    return diffs <= stable_diff


def _longest_constant_series(items, value):
    def _longest_constant_series_from_id(id_):
        max_len = 0
        for i in range(id_, len(items)):
            if items[i] != value:
                break
            max_len += 1
        return max_len
    
    max_len = 0
    for i in range(len(items)):
        next_longest_constant_series = _longest_constant_series_from_id(i)
        if next_longest_constant_series > max_len:
            max_len = next_longest_constant_series
    return max_len

In [5]:
days = np.array([12, 16, 20, 32, 24, 22, 12, 18])
# array([ nan,  nan,  nan,  nan,  3.2,  0.8, 10. ,  3.6])

In [7]:
anomalous_days_count(days)

1

In [9]:
stable_days_count(days)

1

In [11]:
max_stable_period(days)

1

In [38]:
def max_stable_period(temperatures):
    temperatures_diff = find_temperatures_diff(temperatures)
    stable_days = temperatures_diff <= 2

    change_points = np.where(np.logical_not(stable_days))[0] + 1
    all_points = np.concatenate(([0], change_points, [len(temperatures)]))

    stable_periods = np.diff(all_points) - 1
    return np.max(stable_periods)

### [Система рекомендаций](https://ru.hexlet.io/challenges/python-numpy-recommendations-exercise)

https://ru.hexlet.io/code_reviews/1588353

https://ru.hexlet.io/challenges/python-numpy-recommendations-exercise/instance

Напишите функцию, get_recommendation(), которая принимает матрицу с данными о покупках и id пользователя и возвращает список id из максимум 3 товаров, которые можно порекомендовать пользователю для покупки

```
# df с покупками представляет собой матрицу, где каждая строка это покупки пользователя с id равным индексу строки
# т.е. покупки пользователя 0 будут [1 2 5 0 0]
# что означает, что он купил 1 товар с id=0, 2 товара с id=1, 5 товаров id=2 и ноль остальных
purchases = np.array([
   [1, 2, 5, 0, 0],
   [1, 1, 0, 1, 4],
   [0, 3, 0, 0, 1],
   [1, 5, 0, 0, 3]])

# получим рекомендации пользователя с id=0
recs = get_recommendation(purchases, 0)
# пользователю предлагаются товары с id=3 и id=4
print(recs) # [4 3]
```
Товар добавляется в рекомендации по принципу - если он куплен у схожих, но не куплен самим пользователем. Для поиска рекомендаций каждого пользователя ограничьтесь только 5 самыми схожими с ним пользователями.

In [75]:
from collections import Counter
import numpy as np


def get_recommendation(purchases, user_id, similar_goods_count=3, similar_purchases_count=5):
    top_similar_goods = _get_top_similar_goods(purchases, user_id, similar_purchases_count).sum(axis=0)
    top_similar_goods_ids = np.argsort(-top_similar_goods)
    filtered_top_similar_goods_ids = top_similar_goods_ids[top_similar_goods[top_similar_goods_ids] != 0]
    return filtered_top_similar_goods_ids[:similar_goods_count]


def _get_top_similar_goods(purchases, user_id, similar_purchases_count):
    user_purchases = purchases[user_id]
    user_goods = np.where(user_purchases > 0, 1, 0)

    top_similar_purchases = _get_top_similar_purchases(purchases, user_id, similar_purchases_count)
    top_similar_goods = np.where(top_similar_purchases > 0, 1, 0)
    top_similar_goods[:, user_goods == 1] = 0
    return top_similar_goods


def _get_top_similar_purchases(purchases, user_id, count):
    users_purchases = purchases[user_id]
    corrcoefs = np.corrcoef(users_purchases, purchases)[0,1:]

    sorted_ids = np.argsort(-corrcoefs)
    top_similar_ids = sorted_ids[sorted_ids != user_id][:count]
    top_similar_purchases = purchases[top_similar_ids]
    return top_similar_purchases

In [55]:
# Debug version

def get_recommendation(purchases, user_id, similar_goods_count=3, similar_purchases_count=5):
    top_similar_goods = _get_top_similar_goods(purchases, user_id, similar_purchases_count).sum(axis=0)
    print(f'top_similar_goods:\n{top_similar_goods}\n')
    top_similar_goods_ids = np.argsort(-top_similar_goods)
    print(f'top_similar_goods_ids:\n{top_similar_goods_ids}\n')
    filtered_top_similar_goods_ids = top_similar_goods_ids[top_similar_goods[top_similar_goods_ids] != 0]
    print(f'filtered_top_similar_goods_ids:\n{filtered_top_similar_goods_ids}\n')
    return filtered_top_similar_goods_ids[:similar_goods_count]


def _get_top_similar_goods(purchases, user_id, similar_purchases_count):
    user_purchases = purchases[user_id]
    user_goods = np.where(user_purchases > 0, 1, 0)

    top_similar_purchases = _get_top_similar_purchases(purchases, user_id, similar_purchases_count)
    top_similar_goods = np.where(top_similar_purchases > 0, 1, 0)
    top_similar_goods[:, user_goods == 1] = 0
    return top_similar_goods


def _get_top_similar_purchases(purchases, user_id, count):
    users_purchases = purchases[user_id]
    corrcoefs = np.corrcoef(users_purchases, purchases)[0,1:]

    sorted_ids = np.argsort(-corrcoefs)
    top_similar_ids = sorted_ids[sorted_ids != user_id][:count]
    top_similar_purchases = purchases[top_similar_ids]
    return top_similar_purchases

In [61]:
print(np.__version__)

1.26.4


```
/usr/src/app$ cat find_bug.py 
import numpy as np

array = np.array([0, 5, 0, 5, 0, 5, 0, 5, 0, 5])
array_descending_value_ids = np.argsort(-array)
print(array_descending_value_ids)
print(np.__version__)
/usr/src/app$ python3 ./find_bug.py 
[1 3 7 5 9 2 4 0 6 8]
2.1.1
```