In [1]:
import numpy as np

In [2]:
simple_list = [1, 2, 3, 4, 5]

In [3]:
my_first_ndarray = np.array(simple_list, dtype=int)

In [4]:
type(my_first_ndarray)

numpy.ndarray

In [5]:
my_first_ndarray

array([1, 2, 3, 4, 5])

In [6]:
from_ndarray = my_first_ndarray.tolist()

In [7]:
from_ndarray

[1, 2, 3, 4, 5]

In [8]:
type(from_ndarray)

list

In [9]:
my_first_ndarray.dtype

dtype('int64')

In [10]:
str_array = np.array([1, 2, 3], dtype=str)

In [11]:
str_array

array(['1', '2', '3'], dtype='<U1')

In [12]:
str_array.dtype

dtype('<U1')

In [13]:
float_array = np.array([1, 2, 3], dtype=float)

In [15]:
float_array.dtype

dtype('float64')

In [16]:
float_array.dtype.type

numpy.float64

In [17]:
type(float_array.dtype)

numpy.dtype[float64]

In [18]:
type(float_array.dtype.type)

type

In [20]:
orders_list = [7, 4, 3, 8, 15, 21, 25]

# Конвертируем созданный список в массив Numpy
orders_ndarray = np.array(orders_list, dtype=int)

# Тип созданного объекта
print(type(orders_ndarray))
# => <class 'numpy.ndarray'>

# Результат стандартного вывода
print(orders_ndarray)
# => [ 7  4  3  8 15 21 25]

<class 'numpy.ndarray'>
[ 7  4  3  8 15 21 25]


In [21]:
orders_ndarray.min()

3

In [22]:
orders_ndarray.argmin()

2

In [23]:
orders_list =  [
    [7, 1, 7, 8],
    [4, 2, 4, 5],
    [3, 5, 2, 3],
    [8, 12, 8, 7],
    [15, 11, 13, 9],
    [21, 18, 17, 21],
    [25, 16, 25, 17]
]

# Конвертируем созданный «список списков» в массив Numpy
orders_ndarray = np.array(orders_list, dtype=int)

In [24]:
orders_ndarray.min()

1

In [25]:
orders_ndarray.argmin()

1

In [1]:
import random
random.seed(42)
min_num = 1200
max_num = 2500
input_click_numbers = [random.randrange(min_num, max_num) for _ in range(365)]

In [2]:
input_click_numbers[:10]

[1428, 1251, 1763, 1701, 1657, 1485, 1409, 2316, 1378, 2409]

In [3]:
def test_numpy_version(capsys):
    expected = '1.0.0'
    assert np.__version__ >= expected

In [7]:
test_numpy_version(np.__version__)

In [8]:
np.__version__

'1.24.3'

In [9]:
def create_click_numbers_ndarray(numbers_array):
    return np.array(numbers_array)

In [10]:
click_numbers = create_click_numbers_ndarray(input_click_numbers)

In [11]:
click_numbers[:10]

array([1428, 1251, 1763, 1701, 1657, 1485, 1409, 2316, 1378, 2409])

In [15]:
len(click_numbers.shape)


1

In [17]:
click_numbers.max() - click_numbers.min()

1297

In [19]:
click_numbers.mean()

1829.0191780821917

In [20]:
click_numbers.argmax()

362

In [21]:
click_numbers.argmin()

156

In [ ]:
def make_click_numbers(numbers_array):
    return np.array(numbers_array)


def get_range(data):
    return data.max() - data.min()


def get_mean(data):
    return data.mean()


def get_max_clicks_day(data):
    return data.argmax() + 1


def get_min_clicks_day(data):
    return data.argmin() + 1

## Индексы, срезы и итеративный обход 

In [7]:
numbers_lists = [
    [0, 1, 2,],
    [3, 4, 5,],
    [6, 7, 8,],
    [9, 10, 11]
]

numpy_numbers_lists = np.array(numbers_lists)

In [8]:
numpy_numbers_lists

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
numpy_numbers_lists[0,:]

array([0, 1, 2])

In [13]:
numpy_numbers_lists[:,0]

array([0, 3, 6, 9])

In [14]:
numpy_numbers_lists[::-1]

array([[ 9, 10, 11],
       [ 6,  7,  8],
       [ 3,  4,  5],
       [ 0,  1,  2]])

In [15]:
numpy_numbers_lists[:,::2]

array([[ 0,  2],
       [ 3,  5],
       [ 6,  8],
       [ 9, 11]])

In [20]:
orders_values =  [
    [7, 1, 7, 8],
    [4, 2, 4, 5],
    [3, 5, 2, 3],
    [8, 12, 8, 7],
    [15, 11, 13, 9],
    [21, 18, 17, 21],
    [25, 16, 25, 17]
]
orders = np.array(orders)

In [22]:
# Задача 1. Оставить только первые два магазина:

orders[:,:2]

array([[ 7,  1],
       [ 4,  2],
       [ 3,  5],
       [ 8, 12],
       [15, 11],
       [21, 18],
       [25, 16]])

In [23]:
# Задача 2. Оставить в рассмотрении данные продаж за выходные дни:

orders[5:]

array([[21, 18, 17, 21],
       [25, 16, 25, 17]])

In [24]:
# Сделать обратный порядок дней в таблице:

orders[::-1]

array([[25, 16, 25, 17],
       [21, 18, 17, 21],
       [15, 11, 13,  9],
       [ 8, 12,  8,  7],
       [ 3,  5,  2,  3],
       [ 4,  2,  4,  5],
       [ 7,  1,  7,  8]])

#### Самостоятельная работа

In [5]:
clicks_values = [
    [319, 265, 319, 328],
    [292, 274, 292, 301],
    [283, 301, 274, 283],
    [328, 364, 328, 319],
    [391, 355, 373, 337],
    [445, 418, 409, 445],
    [481, 400, 481, 409],
    [333, 267, 333, 344],
    [300, 278, 300, 311],
    [289, 311, 278, 289],
    [344, 388, 344, 333],
    [421, 377, 399, 355],
    [487, 454, 443, 487],
    [531, 432, 531, 443],
    [312, 264, 312, 320],
    [288, 272, 288, 296],
    [280, 296, 272, 280],
    [320, 352, 320, 312],
    [376, 344, 360, 328],
    [424, 400, 392, 424],
    [456, 384, 456, 392],
    [347, 269, 347, 360],
    [308, 282, 308, 321],
    [295, 321, 282, 295],
    [360, 412, 360, 347],
    [451, 399, 425, 373],
    [529, 490, 477, 529],
    [581, 464, 581, 477]
]

In [8]:
def create_click_numbers_ndarray(clicks_values: list) -> np.ndarray:
    return np.array(clicks_values)

In [9]:
clicks_values = create_click_numbers_ndarray(clicks_values)

In [20]:
def get_max_weekly(clicks_values: np.ndarray) -> list:
    return [clicks_values[i * 7:(i + 1) * 7].max() for i in range(4)]

In [21]:
get_max_weekly(clicks_values)

[481, 531, 456, 581]

In [70]:
def get_min_weekly(clicks_values: np.ndarray) -> list:
    return [clicks_values[i * 7:(i + 1) * 7].min() for i in range(4)]

In [71]:
get_min_weekly(clicks_values)

[265, 267, 264, 269]

In [50]:
def get_mean_monday(clicks_values: np.ndarray) -> float:
    return clicks_values[::7].mean()

In [51]:
get_mean_monday(clicks_values)

314.9375

In [62]:
def get_max_click(clicks_values: np.ndarray, col_number: int) -> int:
    return clicks_values[:,col_number].max()

In [64]:
assert round(get_max_click(clicks_values, 0)) == 581
assert round(get_max_click(clicks_values, 1)) == 490
assert round(get_max_click(clicks_values, 2)) == 581
assert round(get_max_click(clicks_values, 3)) == 529

In [76]:
def get_day_of_week_mean(clicks_values: np.ndarray) -> list:
    return [clicks_values[i::7].mean() for i in range(7)]

In [77]:
get_day_of_week_mean(clicks_values)

[314.9375, 294.4375, 289.3125, 345.6875, 379.0, 453.3125, 468.6875]

In [ ]:
def get_placement_max_clicks(clicks_values: np.ndarray) -> list:
    return [clicks_values[i::7].max() for i in range(7)]

## Переформатирование, изменение формы

### https://ru.hexlet.io/courses/python-numpy/lessons/form-change/theory_unit

In [84]:
one_dimension_array = np.array(
    [0,1,2,3,4,5,6,7,8,9,10,11]
)

two_dimensions_array = np.array(
    [
        [0,1,2],
        [3,4,5],
        [6,7,8],
        [9,10,11]
    ]
)


three_dimensions_array = np.array(
    [
        [
            [0,1],
            [2,3],
        ],
        [
            [4,5],
            [6,7],
        ],
        [
            [8,9],
            [10,11]
        ]
    ]
)

In [83]:
one_dimension_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [85]:
two_dimensions_array

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [90]:
two_dimensions_array.shape

(4, 3)

In [86]:
three_dimensions_array

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [87]:
one_dimension_array.shape

(12,)

In [88]:
two_dimensions_array.shape

(4, 3)

In [89]:
three_dimensions_array.shape

(3, 2, 2)

In [91]:
one_dimension_array.reshape((4, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [92]:
two_dimensions_array

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [95]:
two_dimensions_array.reshape((12,))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [100]:
np.array(
    [
        [0,1,2],
        [3,4,0],
    ]
)

array([[0, 1, 2],
       [3, 4, 0]])

In [104]:
one_dimension_array.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [109]:
one_dimension_array.reshape(((4,3)))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [107]:
one_dimension_array.reshape(((4, -2)))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

### Самостоятельная работа

In [54]:
import random
random.seed(42)
min_num = 1200
max_num = 2500

input_click_numbers = [random.randrange(min_num, max_num) for _ in range(280)]

In [55]:
# клики идут последовательно с первого по десятый магазин с понедельника по воскресенье и представлены в виде списка числовых значений без пропусков.

input_click_numbers[:19]

[1428,
 1251,
 1763,
 1701,
 1657,
 1485,
 1409,
 2316,
 1378,
 2409,
 2064,
 1265,
 1261,
 1391,
 1647,
 1676,
 2234,
 2432,
 1254]

In [50]:
def create_weekly_clicks_table(input_click_numbers: list) -> np.ndarray:
    return  np.array(input_click_numbers).reshape((-1, 7, 10))

In [51]:
weekly_clicks_table = create_weekly_clicks_table(input_click_numbers)

In [53]:
weekly_clicks_table[:2]

array([[[1428, 1251, 1763, 1701, 1657, 1485, 1409, 2316, 1378, 2409],
        [2064, 1265, 1261, 1391, 1647, 1676, 2234, 2432, 1254, 2349],
        [1607, 2316, 2059, 1651, 2119, 2406, 1769, 1213, 1526, 2065],
        [1896, 1769, 1518, 1640, 1889, 1409, 1389, 1978, 1398, 1935],
        [1904, 2436, 1741, 1288, 2140, 2298, 1455, 1975, 1361, 2330],
        [1800, 2487, 2466, 1940, 2382, 1593, 1342, 1293, 1666, 1792],
        [1363, 1676, 1406, 1978, 1769, 2128, 1947, 1533, 1958, 1927]],

       [[1629, 1746, 1346, 2447, 1550, 2293, 1701, 1534, 2146, 1977],
        [1752, 2340, 1649, 1864, 1314, 1669, 1265, 1846, 2021, 1748],
        [1335, 1632, 2361, 1844, 1635, 2222, 2010, 2139, 1492, 1742],
        [1485, 1705, 2349, 2303, 1738, 2397, 2077, 2395, 2017, 1941],
        [1649, 1483, 2243, 2210, 1386, 1296, 1424, 1513, 2485, 1527],
        [2064, 2421, 1330, 1988, 1981, 2420, 2158, 2283, 1714, 2333],
        [1223, 1434, 2299, 1746, 1896, 1428, 1801, 2090, 1523, 2129]]])

In [56]:

image_mnist = [
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 17, 17, 17, 17, 81, 180, 180, 35, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 139, 253, 253, 253, 253, 253, 253, 253, 48, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 60, 228, 253, 253, 253, 253, 253, 253, 253, 207, 197, 46, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 213, 253, 253, 253, 253, 253, 253, 253, 253, 253, 253, 223, 52, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 66, 231, 253, 253, 253, 108, 40, 40, 115, 244, 253, 253, 134, 3, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 63, 114, 114, 114, 37, 0, 0, 0, 205, 253, 253, 253, 15, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 57, 253, 253, 253, 15, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 42, 253, 253, 253, 15, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 95, 253, 253, 253, 15, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 205, 253, 253, 253, 15, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 61, 99, 96, 0, 0, 45, 224, 253, 253, 195, 10, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 11, 25, 105, 83, 189, 189, 228, 253, 251, 189, 189, 218, 253, 253, 210, 27, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 42, 116, 173, 253, 253, 253, 253, 253, 253, 253, 253, 253, 253, 253, 253, 253, 221, 116, 7, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 118, 253, 253, 253, 253, 245, 212, 222, 253, 253, 253, 253, 253, 253, 253, 253, 253, 253, 160, 15, 0, 0, 0, 0,
    0, 0, 0, 0, 254, 253, 253, 253, 189, 99, 0, 32, 202, 253, 253, 253, 240, 122, 122, 190, 253, 253, 253, 174, 0, 0, 0, 0,
    0, 0, 0, 0, 255, 253, 253, 253, 238, 222, 222, 222, 241, 253, 253, 230, 70, 0, 0, 17, 175, 229, 253, 253, 0, 0, 0, 0,
    0, 0, 0, 0, 158, 253, 253, 253, 253, 253, 253, 253, 253, 205, 106, 65, 0, 0, 0, 0, 0, 62, 244, 157, 0, 0, 0, 0,
    0, 0, 0, 0, 6, 26, 179, 179, 179, 179, 179, 30, 15, 10, 0, 0, 0, 0, 0, 0, 0, 0, 14, 6, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
]



In [58]:
np.array(image_mnist).shape

(784,)

In [62]:
round(np.array(image_mnist).shape[0] ** 0.5)

28

In [63]:
def mnist_data_converter(image_mnist) -> np.ndarray:
    size = round(len(image_mnist) ** 0.5)
    return np.array(image_mnist).reshape((size, -1))

In [64]:
image = mnist_data_converter(image_mnist)

In [65]:
image

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  10,  17,  17,
         17,  17,  81, 180, 180,  35,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 139, 253, 253,
        253, 253, 253, 253, 253,  48,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  

In [39]:
def vec2word(code_array: list) -> np.ndarray:
    code_rules = {
        (0,2,1) : 'мама',
        (1,3,0) : 'мыла',
        (1,1,2) : 'раму'
    }
    word_len = len(next(iter(code_rules)))
    np_code_array = np.array(code_array).reshape((-1, word_len))
    return [code_rules[tuple(code)] for code in np_code_array]

In [40]:
code_array = [1, 3, 0, 0, 2, 1, 0, 2, 1, 1, 1, 2, 1, 3, 0, 0, 2, 1]

In [41]:
vec2word(code_array)

['мыла', 'мама', 'мама', 'раму', 'мыла', 'мама']

### Упражнения

In [36]:
def create_weekly_sells_table(sells: list, number_of_shops=10):
    return np.array(sells).reshape((-1,7,3))

In [37]:
sells = [7, 6, 12, 5, 3, 3, 8, 11, 12, 9, 5, 7, 4, 3, 9, 10, 8, 6, 3, 15, 2,7, 6, 12, 5, 3, 3, 8, 11, 12, 9, 5, 7, 4, 3, 9, 10, 8, 6, 3, 15, 2]

In [38]:
create_weekly_sells_table(sells, 3)

array([[[ 7,  6, 12],
        [ 5,  3,  3],
        [ 8, 11, 12],
        [ 9,  5,  7],
        [ 4,  3,  9],
        [10,  8,  6],
        [ 3, 15,  2]],

       [[ 7,  6, 12],
        [ 5,  3,  3],
        [ 8, 11, 12],
        [ 9,  5,  7],
        [ 4,  3,  9],
        [10,  8,  6],
        [ 3, 15,  2]]])

## Переформатирование и слияние

### Одномерные структуры данных

In [42]:
arr1 = np.array([0, 1, 2, 3,])
arr2 = np.array([4, 5, 6, 7])

In [44]:
np.concatenate([arr1, arr2])

array([0, 1, 2, 3, 4, 5, 6, 7])

In [46]:
np.hstack([arr1, arr2])

array([0, 1, 2, 3, 4, 5, 6, 7])

In [47]:
np.vstack([arr1, arr2])

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [48]:
np.array([arr1, arr2])

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [50]:
np.column_stack([arr1, arr2])

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [53]:
np.array(list(zip(arr1, arr2)))

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

### Двумерные структуры данных

In [54]:
arr1 = np.array([[5, 8], [8, 9]])
arr2 = np.array([[3, 1], [7, 2]])

In [55]:
np.vstack([arr1, arr2])

array([[5, 8],
       [8, 9],
       [3, 1],
       [7, 2]])

In [57]:
np.concatenate([arr1, arr2])

array([[5, 8],
       [8, 9],
       [3, 1],
       [7, 2]])

In [56]:
np.hstack([arr1, arr2])

array([[5, 8, 3, 1],
       [8, 9, 7, 2]])

In [58]:
np.concatenate([arr1, arr2], axis = 1)

array([[5, 8, 3, 1],
       [8, 9, 7, 2]])

### Многомерные структуры данных

In [59]:
response_values_day1 = np.array([7, 1, 7, 8])
response_values_day2 = np.array([4, 2, 4, 5])
response_values_day3 = np.array([3, 5, 2, 3])

In [64]:
orders = np.vstack([
    response_values_day1,
    response_values_day2,
    response_values_day3,
])

In [65]:
orders

array([[7, 1, 7, 8],
       [4, 2, 4, 5],
       [3, 5, 2, 3]])

In [66]:
orders.T

array([[7, 4, 3],
       [1, 2, 5],
       [7, 4, 2],
       [8, 5, 3]])

### Самостоятельная работа

In [1]:
мама = (0,2,1)
мыла = (1,3,0)
раму = (1,1,2)

In [3]:
# получает на вход список слов и кодирует их в список чисел


In [37]:
word_array = ['мыла', 'мама', 'мама', 'раму', 'мыла', 'мама']

In [38]:
word2vec(word_array)

array([1, 3, 0, 0, 2, 1, 0, 2, 1, 1, 1, 2, 1, 3, 0, 0, 2, 1])

In [2]:
# получает на вход список слов и кодирует их в матричное представление (массив numpy.ndarray)
def word2matrix(word_array: list) -> np.ndarray:
    word_codes = {
        'мама': (0, 2, 1),
        'мыла': (1, 3, 0),
        'раму': (1, 1, 2)
    }
    codes_array = [word_codes[word] for word in word_array]
    return np.vstack(codes_array)

In [43]:
word2matrix(word_array)    

array([[1, 3, 0],
       [0, 2, 1],
       [0, 2, 1],
       [1, 1, 2],
       [1, 3, 0],
       [0, 2, 1]])

## Фильтрация значений и вырезание

In [28]:
 base_array = np.array([0, 1, 2, 3, 4, 5, 6, 7,])

In [29]:
base_array[base_array < 3]

array([0, 1, 2])

In [30]:
filtered_array = np.fromiter(
    (base_array_element for base_array_element in base_array if base_array_element < 3),
    dtype = base_array.dtype
)

In [31]:
filtered_array

array([0, 1, 2])

In [32]:
np.where(base_array < 3, base_array, 0)

array([0, 1, 2, 0, 0, 0, 0, 0])

In [33]:
compare_masks = (base_array > 5) | (base_array < 3)
np.where(compare_masks, base_array, 0)

array([0, 1, 2, 0, 0, 0, 6, 7])

In [34]:
raw_array = np.array([0, 1, None, 3, 4, None, 6, 7,], dtype=np.float64)
raw_array

array([ 0.,  1., nan,  3.,  4., nan,  6.,  7.])

In [35]:
nan_mask = np.isnan(raw_array)

In [36]:
raw_array[~nan_mask]

array([0., 1., 3., 4., 6., 7.])

In [39]:
raw_array[~np.isnan(raw_array)]

array([0., 1., 3., 4., 6., 7.])

In [40]:
np.where(np.isnan(raw_array), 0, raw_array)

array([0., 1., 0., 3., 4., 0., 6., 7.])

In [41]:
orders_values =  [
    [7, 1, -7, None],
    [1000, 2, 4, None],
    [3, None, 503, 3],
    [8, 12, 8, 7],
    [15, 11, None, 9],
    [None, 18, 17, -21],
    [252, 16, 25, 17]
]

In [50]:
orders = np.array(orders_values, dtype=np.float64)
orders

array([[   7.,    1.,   -7.,   nan],
       [1000.,    2.,    4.,   nan],
       [   3.,   nan,  503.,    3.],
       [   8.,   12.,    8.,    7.],
       [  15.,   11.,   nan,    9.],
       [  nan,   18.,   17.,  -21.],
       [ 252.,   16.,   25.,   17.]])

In [51]:
print(orders)

[[   7.    1.   -7.   nan]
 [1000.    2.    4.   nan]
 [   3.   nan  503.    3.]
 [   8.   12.    8.    7.]
 [  15.   11.   nan    9.]
 [  nan   18.   17.  -21.]
 [ 252.   16.   25.   17.]]


In [52]:
negative_values = orders < 0
big_values = orders > 200
nan_values = np.isnan(orders)

In [53]:
normal_mask = ~negative_values & ~big_values & ~nan_values

In [54]:
normal_mask

array([[ True,  True, False, False],
       [False,  True,  True, False],
       [ True, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True, False,  True],
       [False,  True,  True, False],
       [False,  True,  True,  True]])

In [55]:
normal_values = orders[normal_mask]

In [56]:
normal_values

array([ 7.,  1.,  2.,  4.,  3.,  3.,  8., 12.,  8.,  7., 15., 11.,  9.,
       18., 17., 16., 25., 17.])

In [59]:
normal_mean = int(normal_values.mean())

In [60]:
normal_mean

10

In [62]:
np.where(normal_mask, orders, normal_mean)

array([[ 7.,  1., 10., 10.],
       [10.,  2.,  4., 10.],
       [ 3., 10., 10.,  3.],
       [ 8., 12.,  8.,  7.],
       [15., 11., 10.,  9.],
       [10., 18., 17., 10.],
       [10., 16., 25., 17.]])

In [63]:
orders

array([[   7.,    1.,   -7.,   nan],
       [1000.,    2.,    4.,   nan],
       [   3.,   nan,  503.,    3.],
       [   8.,   12.,    8.,    7.],
       [  15.,   11.,   nan,    9.],
       [  nan,   18.,   17.,  -21.],
       [ 252.,   16.,   25.,   17.]])

In [65]:
np.where(~normal_mask, normal_mean, orders)

array([[ 7.,  1., 10., 10.],
       [10.,  2.,  4., 10.],
       [ 3., 10., 10.,  3.],
       [ 8., 12.,  8.,  7.],
       [15., 11., 10.,  9.],
       [10., 18., 17., 10.],
       [10., 16., 25., 17.]])

In [66]:
np.where(normal_mask, orders, normal_mean)

array([[ 7.,  1., 10., 10.],
       [10.,  2.,  4., 10.],
       [ 3., 10., 10.,  3.],
       [ 8., 12.,  8.,  7.],
       [15., 11., 10.,  9.],
       [10., 18., 17., 10.],
       [10., 16., 25., 17.]])

### Самостоятельная работа

In [5]:


clicks_values =  [
    [319, -265, 319, 328],
    [292, 274, 292, 301],
    [283, 301, 274, 283],
    [328, 364, 328, None],
    [391, 355, 373, 337],
    [445, 418, 409, 445],
    [481, 400, 481, 409],
    [None, 267, 333, 344],
    [300, 278, 300, 311],
    [289, 311, -278, 289],
    [344, 388, 344, 333],
    [421, 377, 399, 355],
    [487, 454, -443, 487],
    [531, 432, 531, 443],
    [312, 264, 312, 320],
    [288, None, 288, 296],
    [280, 296, 272, -280],
    [320, 352, 320, 312],
    [376, 344, 360, 328],
    [-424, 400, 392, 424],
    [456, 384, 456, 392],
    [347, 269, 347, 360],
    [308, 282, 308, 321],
    [295, 321, 282, None],
    [360, 412, 360, 347],
    [None, 399, 425, 373],
    [529, 490, 477, 529],
    [581, 464, 581, -477]
]

clicks_values = np.array(clicks_values, dtype=np.float64)
clicks_values

array([[ 319., -265.,  319.,  328.],
       [ 292.,  274.,  292.,  301.],
       [ 283.,  301.,  274.,  283.],
       [ 328.,  364.,  328.,   nan],
       [ 391.,  355.,  373.,  337.],
       [ 445.,  418.,  409.,  445.],
       [ 481.,  400.,  481.,  409.],
       [  nan,  267.,  333.,  344.],
       [ 300.,  278.,  300.,  311.],
       [ 289.,  311., -278.,  289.],
       [ 344.,  388.,  344.,  333.],
       [ 421.,  377.,  399.,  355.],
       [ 487.,  454., -443.,  487.],
       [ 531.,  432.,  531.,  443.],
       [ 312.,  264.,  312.,  320.],
       [ 288.,   nan,  288.,  296.],
       [ 280.,  296.,  272., -280.],
       [ 320.,  352.,  320.,  312.],
       [ 376.,  344.,  360.,  328.],
       [-424.,  400.,  392.,  424.],
       [ 456.,  384.,  456.,  392.],
       [ 347.,  269.,  347.,  360.],
       [ 308.,  282.,  308.,  321.],
       [ 295.,  321.,  282.,   nan],
       [ 360.,  412.,  360.,  347.],
       [  nan,  399.,  425.,  373.],
       [ 529.,  490.,  477.,  529.],
 

In [43]:
# возвращает количество отрицательных значений в данных
def get_negative_values_number(clicks_values: np.ndarray):
    negative_values_mask = clicks_values < 0
    return negative_values_mask.sum()

In [44]:
get_negative_values_number(clicks_values)

6

In [35]:
# возвращает количество пропусков (np.nan) значений в данных
def get_nan_values_number(clicks_values: np.ndarray):
    nan_values_mask = (np.isnan(clicks_values))
    return nan_values_mask.sum()

In [36]:
get_nan_values_number(clicks_values)

5

In [51]:
# возвращает массив с исправленными отрицательными значениями на абсолютные
def fillneg_values_number(clicks_values: np.ndarray):
    return np.where(clicks_values < 0, -clicks_values, clicks_values)

In [52]:
fillneg_values_number(clicks_values)

array([[319., 265., 319., 328.],
       [292., 274., 292., 301.],
       [283., 301., 274., 283.],
       [328., 364., 328.,  nan],
       [391., 355., 373., 337.],
       [445., 418., 409., 445.],
       [481., 400., 481., 409.],
       [ nan, 267., 333., 344.],
       [300., 278., 300., 311.],
       [289., 311., 278., 289.],
       [344., 388., 344., 333.],
       [421., 377., 399., 355.],
       [487., 454., 443., 487.],
       [531., 432., 531., 443.],
       [312., 264., 312., 320.],
       [288.,  nan, 288., 296.],
       [280., 296., 272., 280.],
       [320., 352., 320., 312.],
       [376., 344., 360., 328.],
       [424., 400., 392., 424.],
       [456., 384., 456., 392.],
       [347., 269., 347., 360.],
       [308., 282., 308., 321.],
       [295., 321., 282.,  nan],
       [360., 412., 360., 347.],
       [ nan, 399., 425., 373.],
       [529., 490., 477., 529.],
       [581., 464., 581., 477.]])

In [53]:
# возвращает массив где пропуски заполнены нулями
def fill_nan_values(clicks_values: np.ndarray):
    return np.where(np.isnan(clicks_values), 0, clicks_values)

In [54]:
fillneg_values_number(clicks_values)

array([[ 319., -265.,  319.,  328.],
       [ 292.,  274.,  292.,  301.],
       [ 283.,  301.,  274.,  283.],
       [ 328.,  364.,  328.,    0.],
       [ 391.,  355.,  373.,  337.],
       [ 445.,  418.,  409.,  445.],
       [ 481.,  400.,  481.,  409.],
       [   0.,  267.,  333.,  344.],
       [ 300.,  278.,  300.,  311.],
       [ 289.,  311., -278.,  289.],
       [ 344.,  388.,  344.,  333.],
       [ 421.,  377.,  399.,  355.],
       [ 487.,  454., -443.,  487.],
       [ 531.,  432.,  531.,  443.],
       [ 312.,  264.,  312.,  320.],
       [ 288.,    0.,  288.,  296.],
       [ 280.,  296.,  272., -280.],
       [ 320.,  352.,  320.,  312.],
       [ 376.,  344.,  360.,  328.],
       [-424.,  400.,  392.,  424.],
       [ 456.,  384.,  456.,  392.],
       [ 347.,  269.,  347.,  360.],
       [ 308.,  282.,  308.,  321.],
       [ 295.,  321.,  282.,    0.],
       [ 360.,  412.,  360.,  347.],
       [   0.,  399.,  425.,  373.],
       [ 529.,  490.,  477.,  529.],
 

### Упражнения

## Быстрые поэлементные операции

In [2]:
arr1 = np.array([0, 1, 2, 3, 4, 5, 6, 7])

In [3]:
arr1 + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [4]:
matrix_array = np.array([[5, 8], [8, 9]])
vector_array = np.array([1, 2])

In [5]:
matrix_array + vector_array

array([[ 6, 10],
       [ 9, 11]])

In [6]:
arr1 = [0, 1, 2, 3, 4, 5, 6, 7]
change_array_value = 5
arr2 = [2, 2, 2, 2, -1, -1, -1, -1]

In [7]:
# sum_ = list(zip(sum() for ))

In [8]:
list(zip(arr1, arr2))

[(0, 2), (1, 2), (2, 2), (3, 2), (4, -1), (5, -1), (6, -1), (7, -1)]

In [9]:
list(sum(e) for e in zip(arr1, arr2))

[2, 3, 4, 5, 3, 4, 5, 6]

In [10]:
list(e1 + e2 for e1, e2 in zip(arr1, arr2))

[2, 3, 4, 5, 3, 4, 5, 6]

In [11]:
arr1 = np.array([[5, 8], [8, 9]])
arr2 = np.array([[3, 1], [7, 2]])

In [12]:
arr1

array([[5, 8],
       [8, 9]])

In [13]:
arr2

array([[3, 1],
       [7, 2]])

In [14]:
arr1 * arr2

array([[15,  8],
       [56, 18]])

### Как это работает на практике

In [17]:
orders =  [
    [7, 1, 7, 8],
    [4, 2, 4, 5],
    [3, 5, 2, 3],
    [8, 12, 8, 7],
    [15, 11, 13, 9],
    [21, 18, 17, 21],
    [25, 16, 25, 17]
]

orders = np.array(orders)

In [18]:
mean_order = orders.mean()

In [19]:
mean_order

10.5

In [20]:
orders - mean_order

array([[-3.5, -9.5, -3.5, -2.5],
       [-6.5, -8.5, -6.5, -5.5],
       [-7.5, -5.5, -8.5, -7.5],
       [-2.5,  1.5, -2.5, -3.5],
       [ 4.5,  0.5,  2.5, -1.5],
       [10.5,  7.5,  6.5, 10.5],
       [14.5,  5.5, 14.5,  6.5]])

In [35]:
mean_by_shops = np.array([orders[:,i].mean() for i in range(4)])

In [36]:
mean_by_shops

array([11.85714286,  9.28571429, 10.85714286, 10.        ])

In [37]:
orders - mean_by_shops

array([[-4.85714286, -8.28571429, -3.85714286, -2.        ],
       [-7.85714286, -7.28571429, -6.85714286, -5.        ],
       [-8.85714286, -4.28571429, -8.85714286, -7.        ],
       [-3.85714286,  2.71428571, -2.85714286, -3.        ],
       [ 3.14285714,  1.71428571,  2.14285714, -1.        ],
       [ 9.14285714,  8.71428571,  6.14285714, 11.        ],
       [13.14285714,  6.71428571, 14.14285714,  7.        ]])

In [38]:
mean_by_shop = orders.mean(axis=0)

In [39]:
mean_by_shop

array([11.85714286,  9.28571429, 10.85714286, 10.        ])

In [40]:
orders - mean_by_shop

array([[-4.85714286, -8.28571429, -3.85714286, -2.        ],
       [-7.85714286, -7.28571429, -6.85714286, -5.        ],
       [-8.85714286, -4.28571429, -8.85714286, -7.        ],
       [-3.85714286,  2.71428571, -2.85714286, -3.        ],
       [ 3.14285714,  1.71428571,  2.14285714, -1.        ],
       [ 9.14285714,  8.71428571,  6.14285714, 11.        ],
       [13.14285714,  6.71428571, 14.14285714,  7.        ]])

In [46]:
mean_by_day = mean_by_day.reshape((7,1))

In [47]:
mean_by_day

array([[ 5.75],
       [ 3.75],
       [ 3.25],
       [ 8.75],
       [12.  ],
       [19.25],
       [20.75]])

In [48]:
orders - mean_by_day

array([[ 1.25, -4.75,  1.25,  2.25],
       [ 0.25, -1.75,  0.25,  1.25],
       [-0.25,  1.75, -1.25, -0.25],
       [-0.75,  3.25, -0.75, -1.75],
       [ 3.  , -1.  ,  1.  , -3.  ],
       [ 1.75, -1.25, -2.25,  1.75],
       [ 4.25, -4.75,  4.25, -3.75]])

### Самостоятельная работа

In [6]:
def min_max_scaler(image_mnist):
    image = np.array(image_mnist)
    min_pixel_value = image.min()
    max_pixel_value = image.max()
    return (image - min_pixel_value) / (max_pixel_value - min_pixel_value)

In [ ]:
def standard_scaler(image_mnist):
    image = np.array(image_mnist)
    mean = image.mean()
    std = image.std()
    return (image - mean) / std

In [7]:
image = [0, 1, 2, 4, 8]

array([0.   , 0.125, 0.25 , 0.5  , 1.   ])

In [ ]:
min_max_scaler(image) # [0.   , 0.125, 0.25 , 0.5  , 1.   ]

In [9]:
standard_scaler(image)

array([-1.06066017, -0.70710678, -0.35355339,  0.35355339,  1.76776695])

## Уход от циклов и векторизованные вычисления

In [10]:
test_matrix = np.array(
    [
        [2, 4, 6],
        [1, 2, 8],
    ]
)

In [11]:
test_matrix.mean()

3.8333333333333335

In [12]:
np.sum(test_matrix, axis=0)

array([ 3,  6, 14])

In [13]:
np.sum(test_matrix, axis=1)

array([12, 11])

In [16]:
# Исходная функция
def fill_over_bound(value, bound):
    '''Limit elements from array a by value b'''
    returned_value = value
    if value > bound:
        returned_value = bound
    return returned_value


# Векторизованный вариант
vectorized_fill_over_bound = np.vectorize(fill_over_bound)

In [17]:
vector_array = [1,2,3,4,5,6]
matrix_array = [[1,6],[14,15]]
bound_value = 4

In [19]:
vectorized_fill_over_bound(vector_array, bound_value)

array([1, 2, 3, 4, 4, 4])

In [20]:
vectorized_fill_over_bound(matrix_array, bound_value)

array([[1, 4],
       [4, 4]])

In [21]:
orders =  [
    [7, 1, 7, 8],
    [4, 2, 4, 5],
    [3, 5, 2, 3],
    [8, 12, 8, 7],
    [15, 11, 13, 9],
    [21, 18, 17, 21],
    [25, 16, 25, 94]
]
orders = np.array(orders)

In [23]:
mean_order = orders.mean()
mean_order

13.25

In [24]:
sigma_val = orders.std()
sigma_val

17.01811010155274

In [26]:
def fill_sigma_values(value, mean_val, sigma_val):
    prepared_value = value
    low_bound = mean_val - sigma_val
    upper_bound = mean_val + sigma_val

    if value < low_bound:
        prepared_value = low_bound
    elif value > upper_bound:
        prepared_value = upper_bound

    return prepared_value


fill_sigma_values = np.vectorize(fill_sigma_values)


In [28]:
fill_sigma_values(orders, mean_order, sigma_val)

array([[ 7,  1,  7,  8],
       [ 4,  2,  4,  5],
       [ 3,  5,  2,  3],
       [ 8, 12,  8,  7],
       [15, 11, 13,  9],
       [21, 18, 17, 21],
       [25, 16, 25, 30]])

In [28]:
# возвращает целочисленный массив средних значений кликов для каждой страницы сайта
def get_int_columns_mean(clicks_values: np.ndarray) -> np.ndarray:
    return clicks_values.mean(axis=0).astype(int)

In [27]:
def get_even_clicks(value: int) -> int:
    return value + 1 if value % 2 else value


get_even_clicks = np.vectorize(get_even_clicks)

In [25]:
clicks_values =  [
    [319, 265, 319, 328],
    [292, 274, 292, 301],
    [283, 301, 274, 283],
    [328, 364, 328, 284],
    [391, 355, 373, 337],
    [445, 418, 409, 445],
    [481, 400, 481, 409],
    [388, 267, 333, 344],
    [531, 278, 300, 311],
    [289, 311, 278, 289],
    [344, 388, 344, 333],
    [421, 377, 399, 355],
    [487, 454, 443, 487],
    [531, 432, 531, 443],
    [312, 264, 312, 320],
    [288, 300, 288, 296],
    [280, 296, 272, 280],
    [320, 352, 320, 312],
    [376, 344, 360, 328],
    [424, 400, 392, 424],
    [456, 384, 456, 392],
    [347, 269, 347, 360],
    [308, 282, 308, 321],
    [295, 321, 282, 392],
    [360, 412, 360, 347],
    [443, 399, 425, 373],
    [529, 490, 477, 529],
    [581, 464, 581, 477]
]

clicks_values = np.array(clicks_values)
clicks_values

array([[319, 265, 319, 328],
       [292, 274, 292, 301],
       [283, 301, 274, 283],
       [328, 364, 328, 284],
       [391, 355, 373, 337],
       [445, 418, 409, 445],
       [481, 400, 481, 409],
       [388, 267, 333, 344],
       [531, 278, 300, 311],
       [289, 311, 278, 289],
       [344, 388, 344, 333],
       [421, 377, 399, 355],
       [487, 454, 443, 487],
       [531, 432, 531, 443],
       [312, 264, 312, 320],
       [288, 300, 288, 296],
       [280, 296, 272, 280],
       [320, 352, 320, 312],
       [376, 344, 360, 328],
       [424, 400, 392, 424],
       [456, 384, 456, 392],
       [347, 269, 347, 360],
       [308, 282, 308, 321],
       [295, 321, 282, 392],
       [360, 412, 360, 347],
       [443, 399, 425, 373],
       [529, 490, 477, 529],
       [581, 464, 581, 477]])

In [30]:
get_int_columns_mean(clicks_values)

array([387, 352, 367, 360])

In [26]:
get_even_clicks(clicks_values)

NameError: name 'get_even_clicks' is not defined

### Упражнения

In [4]:
def get_stat_values(array: np.ndarray) -> tuple:
    return array.mean(), array.std(), np.median(array)

In [23]:
def get_min_value_position(array: np.ndarray) -> tuple:
    return np.unravel_index(np.argmin(array), array.shape)

In [20]:
items = np.array([
    [4,5,6],
    [3,1,4],
    [5,0,6],
])

In [21]:
get_stat_values(items)

(3.7777777777777777, 1.9876159799998132, 4.0)

In [22]:
get_min_value_position(items)

(2, 1)

In [19]:
items.shape

(3, 3)

## Применение математических и статистических функций

In [32]:
# Продажи за неделю по 4 магазинам

orders =  [
    [7, 1, 7, 8],
    [4, 2, 4, 5],
    [3, 5, 2, 3],
    [8, 12, 8, 7],
    [15, 11, 13, 9],
    [21, 86, 35, 16],
    [70, 90, 124, 94]
]
orders = np.array(orders)

In [29]:
orders

array([[  7,   1,   7,   8],
       [  4,   2,   4,   5],
       [  3,   5,   2,   3],
       [  8,  12,   8,   7],
       [ 15,  11,  13,   9],
       [ 21,  86,  35,  16],
       [ 70,  90, 124,  94]])

In [30]:
orders.sum(axis=0)

array([128, 207, 193, 142])

In [31]:
orders.sum(axis=1)

array([ 23,  15,  13,  35,  48, 158, 378])

In [34]:
orders[:,0].max()

70

In [35]:
orders[:,0].argmax()

6

In [42]:
def to_percents(value, total):
    return round(value / total * 100, 1)


to_percents = np.vectorize(to_percents)

In [39]:
to_percents(256, 1000)

26

In [36]:
orders / orders.sum()

array([[0.01044776, 0.00149254, 0.01044776, 0.0119403 ],
       [0.00597015, 0.00298507, 0.00597015, 0.00746269],
       [0.00447761, 0.00746269, 0.00298507, 0.00447761],
       [0.0119403 , 0.01791045, 0.0119403 , 0.01044776],
       [0.02238806, 0.01641791, 0.01940299, 0.01343284],
       [0.03134328, 0.12835821, 0.05223881, 0.0238806 ],
       [0.10447761, 0.13432836, 0.18507463, 0.14029851]])

In [43]:
to_percents(orders, orders.sum())

array([[ 1. ,  0.1,  1. ,  1.2],
       [ 0.6,  0.3,  0.6,  0.7],
       [ 0.4,  0.7,  0.3,  0.4],
       [ 1.2,  1.8,  1.2,  1. ],
       [ 2.2,  1.6,  1.9,  1.3],
       [ 3.1, 12.8,  5.2,  2.4],
       [10.4, 13.4, 18.5, 14. ]])

In [44]:
orders[:, 0]

array([ 7,  4,  3,  8, 15, 21, 70])

In [45]:
orders[:, 0].cumsum()

array([  7,  11,  14,  22,  37,  58, 128])

In [46]:
np.diff(orders, axis=0)

array([[-3,  1, -3, -3],
       [-1,  3, -2, -2],
       [ 5,  7,  6,  4],
       [ 7, -1,  5,  2],
       [ 6, 75, 22,  7],
       [49,  4, 89, 78]])

In [47]:
(orders / orders.sum() * 100).round(1)

array([[ 1. ,  0.1,  1. ,  1.2],
       [ 0.6,  0.3,  0.6,  0.7],
       [ 0.4,  0.7,  0.3,  0.4],
       [ 1.2,  1.8,  1.2,  1. ],
       [ 2.2,  1.6,  1.9,  1.3],
       [ 3.1, 12.8,  5.2,  2.4],
       [10.4, 13.4, 18.5, 14. ]])

In [26]:
# import random
# a = [random.randint(1,20) for _ in range(20)]
a = [4, 16, 9, 18, 13, 11, 20, 4, 11, 7, 5, 18, 11, 5, 1, 13, 10, 18, 10, 1]
a = [10, 7, 9, 10, 5, 14, 18, 4, 17, 16, 10, 2, 12, 8, 2, 4, 10, 20, 9, 5]
a = [15, 4, 6, 6, 8, 16, 14, 14, 12, 14, 4, 16, 9, 5, 19, 3, 17, 19, 13, 2]
a = [2, 15, 7, 13, 19, 14, 5, 7, 16, 19, 18, 8, 6, 3, 10, 11, 4, 10, 14, 20]
a = np.array(a)
a

array([ 2, 15,  7, 13, 19, 14,  5,  7, 16, 19, 18,  8,  6,  3, 10, 11,  4,
       10, 14, 20])

In [27]:
a_sorted = a.copy()
a_sorted.sort()
a_sorted

array([ 2,  3,  4,  5,  6,  7,  7,  8, 10, 10, 11, 13, 14, 14, 15, 16, 18,
       19, 19, 20])

In [28]:
np.percentile(a, 25)


6.75

In [50]:
a.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [31]:
np.percentile(a, 75)

15.25

In [33]:
orders

array([[  7,   1,   7,   8],
       [  4,   2,   4,   5],
       [  3,   5,   2,   3],
       [  8,  12,   8,   7],
       [ 15,  11,  13,   9],
       [ 21,  86,  35,  16],
       [ 70,  90, 124,  94]])

In [34]:
orders[:, 0]

array([ 7,  4,  3,  8, 15, 21, 70])

In [35]:
orders[:, 1]

array([ 1,  2,  5, 12, 11, 86, 90])

In [36]:
np.corrcoef(orders[:, 0], orders[:, 1])

array([[1.        , 0.80868227],
       [0.80868227, 1.        ]])

In [39]:
def get_iqr(array):
    return np.percentile(array, 25), np.percentile(array, 75)

In [40]:
items = np.array([
    [4,5,6],
    [3,1,4],
    [5,8,6],
])


In [42]:
get_iqr(items)

(4.0, 6.0)

In [49]:
def get_correlation(array1, array2):
    return np.corrcoef(array1, array2)[0, 1]

In [50]:
items1 = np.array([
    [4, 5, 6]
])
items2 = np.array([
    [6, 5, 12]
])

In [51]:
get_correlation(items1, items2)

0.7924058156930615