# Python: Numpy-массивы 
[link](https://ru.hexlet.io/courses/python-numpy)

[Конспект](https://drive.google.com/drive/folders/10qe1lthtJ4T2J9rZ-pudLZlf604Pyenw?usp=sharing)

## 2. Многомерные массивы в Numpy

In [1]:
import numpy
import numpy as np

In [11]:
import time

large_list_of_numbers = list(range(1_000_000))

ndarray_of_numbers = numpy.array(large_list_of_numbers)

tries = 500
# Замеряем время выполнения заданного количества итераций
# нахождения максимального элемента списка
start_time = time.time()
for _ in range(tries):
    max(large_list_of_numbers)
end_time = time.time()

print(f'Total time for a large list: {round(end_time - start_time, 2)} s')

# Замеряем время выполнения заданного количества итераций
# нахождения максимального элемента массива Numpy
start_time = time.time()
for _ in range(tries):
    ndarray_of_numbers.max()
end_time = time.time()

print(f'Total time for a ndarray: {round(end_time - start_time, 2)} s')

Total time for a large list: 8.23 s
Total time for a ndarray: 0.7 s


In [12]:
# Создаем простой пример списка языка Python
simple_list = [1, 2, 3, 4, 5]

# Конвертируем созданный список в массив Numpy
my_first_ndarray = np.array(simple_list, dtype=int)

# Тип созданного объекта
print(type(my_first_ndarray))
# => <class 'numpy.ndarray'>

# Результат стандартного вывода
print(my_first_ndarray)
# => [1 2 3 4 5]

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [15]:
my_first_ndarray.dtype.type

numpy.int64

In [14]:
my_first_ndarray.tolist()

[1, 2, 3, 4, 5]

In [17]:
# Целочисленный массив
print(np.array([1, 2, 3], dtype=int).dtype.type)
# => <class 'numpy.int64'>

# Массив строк
print(np.array([1, 2, 3], dtype=str).dtype.type)
# => <class 'numpy.str_'>

# Массив чисел с плавающей запятой
print(np.array([1, 2, 3], dtype=float).dtype.type)
# => <class 'numpy.float64'>

<class 'numpy.int64'>
<class 'numpy.str_'>
<class 'numpy.float64'>


In [16]:
# Все элементы списка целочисленные
print(np.array([1, 2, 3]).dtype.type)
# => <class 'numpy.int64'>

# Все элементы списка — это строки
print(np.array(['1', '2', '3']).dtype.type)
# => <class 'numpy.str_'>

# Элементы списка как текстовые, так и целочисленные
print(np.array(['1', 2, 3]).dtype.type)
# => <class 'numpy.str_'>

<class 'numpy.int64'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [18]:
# Создаем список продаж — представим, что считали его из базы данных
orders_list = [7, 4, 3, 8, 15, 21, 25]

# Конвертируем созданный список в массив Numpy
orders_ndarray = np.array(orders_list, dtype=int)

# Тип созданного объекта
print(type(orders_ndarray))
# => <class 'numpy.ndarray'>

# Результат стандартного вывода
print(orders_ndarray)
# => [ 7  4  3  8 15 21 25]

<class 'numpy.ndarray'>
[ 7  4  3  8 15 21 25]


In [19]:
# Находим минимальный элемент массива
print(orders_ndarray.min())
# => 3

# Находим порядковый номер минимального элемента массива
print(orders_ndarray.argmin())
# => 2

3
2


In [20]:
# Создаем «список списков продаж»
orders_list =  [
    [7, 1, 7, 8],
    [4, 2, 4, 5],
    [3, 5, 2, 3],
    [8, 12, 8, 7],
    [15, 11, 13, 9],
    [21, 18, 17, 21],
    [25, 16, 25, 17]
]

# Конвертируем созданный «список списков» в массив Numpy
orders_ndarray = np.array(orders_list, dtype=int)

# Описываем тип созданного объекта
print(type(orders_ndarray))
# => <class 'numpy.ndarray'>

# Находим минимальный элемент массива
print(orders_ndarray.min())
# => 1

<class 'numpy.ndarray'>
1


### Самостоятельная работа 

In [3]:
# тестовые данные
import random
random.seed(42)
min_num = 1200
max_num = 2500
input_click_numbers = [random.randrange(min_num, max_num) for _ in range(365)]
input_click_numbers[:10]

[1428, 1251, 1763, 1701, 1657, 1485, 1409, 2316, 1378, 2409]

In [10]:
import numpy as np
np.version.version

'1.24.3'

In [11]:
np.__version__

'1.24.3'

In [34]:
def create_nparray(values, type_=int):
    return np.array(values, dtype=type_)

In [36]:
input_click_array = create_nparray(input_click_numbers)
input_click_array[:5]

array([1428, 1251, 1763, 1701, 1657])

In [37]:
def range(array):
    return np.max(array) - np.min(array)

In [28]:
range(input_click_numbers)

1297

In [38]:
np.mean(input_click_array)

1829.0191780821917

In [39]:
abs(np.mean(input_click_array) - range(input_click_array))

532.0191780821917

In [40]:
np.where(input_click_array == np.max(input_click_array))

(array([362]),)

In [41]:
input_click_array.argmax()

362

In [42]:
input_click_array.argmin()

156

### Упражнение 
[link](https://ru.hexlet.io/code_reviews/1237588)

In [46]:
def make_click_numbers(values, dtype_=int):
    return np.array(values, dtype=int)

In [58]:
def get_range(array):
    return array.max() - array.min()

In [59]:
clicks_per_day = make_click_numbers([5, 7, 12, 3])
assert get_range(clicks_per_day) == 9

In [68]:
def get_mean(array):
    return array.mean()

In [61]:
clicks_per_day = make_click_numbers([5, 7, 12, 3])
get_mean(clicks_per_day)  # 6.75

In [65]:
def get_max_clicks_day(array):
    return array.argmax() + 1

In [66]:
def get_min_clicks_day(array):
    return array.argmin() + 1

In [67]:
clicks_per_day = make_click_numbers([5, 7, 12, 3])
assert get_max_clicks_day(clicks_per_day) == 3
assert get_min_clicks_day(clicks_per_day) == 4

## 3. Индексы, срезы и итеративный обход

In [2]:
# Создание списка языка Python
numbers = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# Конвертация созданного списка в массив Numpy
numpy_numbers = np.array(numbers)

# Тип созданного объекта numbers
print(type(numbers))
# => <class 'list'>

# Тип созданного объекта numpy_numbers
print(type(numpy_numbers))
# => <class 'numpy.ndarray'>

<class 'list'>
<class 'numpy.ndarray'>


In [3]:
# Получение элемента по индексу из списка
print(numbers[2])
# => 2

# Получение элемента по индексу из numpy.ndarray
print(numpy_numbers[2])
# => 2

2
2


In [4]:
# Получение элемента по отрицательному индексу из списка
print(numbers[-1])
# => 9

# Получение элемента по отрицательному индексу из numpy.ndarray
print(numpy_numbers[-1])
# => 9

9
9


In [15]:
# Создание списка списков
numbers_lists = [
    [0, 1, 2,],
    [3, 4, 5,],
    [6, 7, 8,],
    [9, 10, 11]
]

# Конвертация созданного списка списков в массив Numpy
numpy_numbers_lists = np.array(numbers_lists)

# Получение элемента по индексу из списка
print(numbers_lists[2][1])
# => 7

# Получение элемента по индексу из numpy.ndarray
print(numpy_numbers_lists[1][1])
# => 4

# Получение элемента по индексу из numpy.ndarray
# Более предпочтительный способ
print(numpy_numbers_lists[2,2])
# => 8

7
4
8


In [16]:
# Срезы
# Первые элементы списка
print(numpy_numbers[:4])
# => [0 1 2 3]

# Середина
print(numpy_numbers[2:5])
# => [2 3 4]

# Последние элементы списка
print(numpy_numbers[-3:])
# => [7 8 9]

[0 1 2 3]
[2 3 4]
[7 8 9]


In [17]:
# Четные элементы массива
print(numpy_numbers[::2])
# => [0 2 4 6 8]

# Обратный порядок элементов массива
print(numpy_numbers[::-1])
# => [9 8 7 6 5 4 3 2 1 0]

[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]


In [18]:
numpy_numbers_lists

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
# Вырезание элементов из numpy.ndarray
print(numpy_numbers_lists[:2,:2])
# => [[0 1]
#     [3 4]]

# Попытка вырезать те же элементы из списка
print(numbers_lists[:2][:2])
# => [[0, 1, 2], [3, 4, 5]]

# Решение для вырезания элементов из списка
print([row[:2] for row in numbers_lists[:2]])
# => [[0, 1], [3, 4]]

[[0 1]
 [3 4]]
[[0, 1, 2], [3, 4, 5]]
[[0, 1], [3, 4]]


In [19]:
# Вырезание 0 строки из numpy.ndarray
print(numpy_numbers_lists[0,:])
# => [0 1 2]

# Вырезание 0 строки — еще один способ
print(numpy_numbers_lists[0])
# => [0 1 2]

# Вырезание 1 столбца из numpy.ndarray
print(numpy_numbers_lists[:,1])
# => [ 1  4  7 10]

[0 1 2]
[0 1 2]
[ 1  4  7 10]


In [22]:
numpy_numbers_lists

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [21]:
# Перестановка строк в обратном порядке
print(numpy_numbers_lists[::-1])
# => [[ 9 10 11]
#     [ 6  7  8]
#     [ 3  4  5]
#     [ 0  1  2]]

# Четные столбцы
print(numpy_numbers_lists[:,::2])
# => [[ 0  2]
#     [ 3  5]
#     [ 6  8]
#     [ 9 11]]

[[ 9 10 11]
 [ 6  7  8]
 [ 3  4  5]
 [ 0  1  2]]
[[ 0  2]
 [ 3  5]
 [ 6  8]
 [ 9 11]]


In [25]:
# Создаем «лист листов» продаж
orders_values =  [
    [7, 1, 7, 8],
    [4, 2, 4, 5],
    [3, 5, 2, 3],
    [8, 12, 8, 7],
    [15, 11, 13, 9],
    [21, 18, 17, 21],
    [25, 16, 25, 17]
]

# Конвертируем созданный «лист листов» в массив Numpy
orders = np.array(orders_values)

In [28]:
# Оставляем только первые два магазина
orders[:,:2]

array([[ 7,  1],
       [ 4,  2],
       [ 3,  5],
       [ 8, 12],
       [15, 11],
       [21, 18],
       [25, 16]])

In [29]:
# Оставляем в рассмотрении данные продаж за выходные дни
orders[-2:,:]

array([[21, 18, 17, 21],
       [25, 16, 25, 17]])

In [31]:
# Делаем обратный порядок дней в таблице
orders[::-1]

array([[25, 16, 25, 17],
       [21, 18, 17, 21],
       [15, 11, 13,  9],
       [ 8, 12,  8,  7],
       [ 3,  5,  2,  3],
       [ 4,  2,  4,  5],
       [ 7,  1,  7,  8]])

### Упражнение
[link](https://ru.hexlet.io/code_reviews/1237579)

In [2]:
# В каждой строке — количество кликов рекламного баннера с четырех площадок
# Каждая строка — дни месяца с понедельника по воскресенье

clicks_values = [
    [319, 265, 319, 328],
    [292, 274, 292, 301],
    [283, 301, 274, 283],
    [328, 364, 328, 319],
    [391, 355, 373, 337],
    [445, 418, 409, 445],
    [481, 400, 481, 409],
    [333, 267, 333, 344],
    [300, 278, 300, 311],
    [289, 311, 278, 289],
    [344, 388, 344, 333],
    [421, 377, 399, 355],
    [487, 454, 443, 487],
    [531, 432, 531, 443],
    [312, 264, 312, 320],
    [288, 272, 288, 296],
    [280, 296, 272, 280],
    [320, 352, 320, 312],
    [376, 344, 360, 328],
    [424, 400, 392, 424],
    [456, 384, 456, 392],
    [347, 269, 347, 360],
    [308, 282, 308, 321],
    [295, 321, 282, 295],
    [360, 412, 360, 347],
    [451, 399, 425, 373],
    [529, 490, 477, 529],
    [581, 464, 581, 477],
    [111, 467, 666, 111],
]

clicks_values = np.array(clicks_values)

In [88]:
def get_max_weekly(data):
    return [data[i:i + 7:].max() for i in range(0,len(data),7)]

In [89]:
get_max_weekly(clicks_values)

[481, 531, 456, 581, 666]

In [74]:
def get_min_weekly(data):
    return [data[i:i + 7:].min() for i in range(0,len(data),7)]

In [76]:
get_min_weekly(clicks_values)

[265, 267, 264, 269]

In [7]:
def get_day_of_week_mean(data):
    return [row.mean() for row in data]

In [9]:
get_day_of_week_mean(clicks_values)[:5]

[307.75, 289.75, 285.25, 334.75, 364.0]

In [85]:
def get_placement_max_clicks(data, column):
    return data[:,column].max()

In [86]:
get_placement_max_clicks(clicks_values, 1)

490

In [5]:
def get_mean_monday(data):
    return data[::7]

In [6]:
get_mean_monday(clicks_values)

array([[319, 265, 319, 328],
       [333, 267, 333, 344],
       [312, 264, 312, 320],
       [347, 269, 347, 360],
       [111, 467, 666, 111]])